name: Format Check

on:
  pull_request:
  workflow_dispatch:

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Run clang-format check
        uses: reviewdog/action-clang-format@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: error
          # 如果是 PR → 只检查改动行；如果是手动触发 → 全量检查
          # filter_mode: ${{ github.event_name == 'pull_request' && 'diff_context' || 'nofilter' }}
          filter_mode: nofilter
          clang_format_version: 16
          pattern: "npc/**/*.{c,cpp,h,hpp}"

  verible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Verible formatter check
        uses: chipsalliance/verible-formatter-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: error
          files: "npc/**/*.{v,sv}"
          # 如果是 PR → 只检查改动行；如果是手动触发 → 全量检查
          # filter_mode: ${{ github.event_name == 'pull_request' && 'diff_context' || 'nofilter' }}
          filter_mode: nofilter
